language: cpp
compiler:
  - gcc
  - clang
sudo: required
script: mkdir build && cd build && cmake .. -GNinja && ninja && ninja tests
dist: trusty
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.9"; CC="clang-3.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-3.9
    packages:
    - ninja-build
    - python3
    - gcc-5
    - g++-5
    - clang-3.9
    - liballegro5-dev
    - liballegro-acodec5-dev
    - liballegro-audio5-dev
    - liballegro-ttf5-dev
    - liballegro-image5-dev
