dist: xenial

language: cpp

compiler: clang

before_install:
  - sudo apt-get install -y clang-6.0 libclang-common-6.0-dev libclang1-6.0 libclang-6.0-dev libfuzzer-6.0-dev  libllvm6.0 libncurses-dev libz-dev llvm-6.0 llvm-6.0-dev llvm-6.0-runtime ninja-build python3

script:
  - cmake .. -GNinja && ninja && ninja tests
