language: cpp
compiler:
  - gcc
  - clang
sudo: required
script: make && make install && make tests
before_install:
  - sudo chmod -R 777 /usr/local/
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - liballegro5-dev
